from __future__ import annotations

import copy
import json
from typing import Any

ICCPLUS_VERSION = "2.10.6"
ICCPLUS_COMMIT = "a420836248d32043ae45d03f1b93cdcb9e354663"
ICCPLUS_REPOSITORY = "wahaha303/ICC-Plus-Svelte"

# These values are transcribed from ICCPlus/src/lib/store/store.svelte.ts at
# ICCPLUS_COMMIT. Field names and even upstream typos are intentionally kept
# verbatim because a newly exported project must match ICC Plus 2.10.6.
FILTER_STYLING: dict[str, Any] = {
    "selFilterBlurIsOn": False,
    "selFilterBlur": 0,
    "selFilterBrightIsOn": False,
    "selFilterBright": 100,
    "selFilterContIsOn": False,
    "selFilterCont": 100,
    "selFilterGrayIsOn": False,
    "selFilterGray": 0,
    "selFilterHueIsOn": False,
    "selFilterHue": 0,
    "selFilterInvertIsOn": False,
    "selFilterInvert": 0,
    "selFilterOpacIsOn": False,
    "selFilterOpac": 100,
    "selFilterSaturIsOn": False,
    "selFilterSatur": 1,
    "selFilterSepiaIsOn": False,
    "selFilterSepia": 0,
    "selBgColorIsOn": True,
    "selOverlayOnImage": False,
    "selFilterBgColor": "#70FF7EFF",
    "selBorderColorIsOn": False,
    "selFilterBorderColor": "#000000FF",
    "selImgBorderColorIsOn": False,
    "selFilterImgBorderColor": "#000000FF",
    "selCTitleColorIsOn": False,
    "selFilterCTitleColor": "#000000FF",
    "selCTextColorIsOn": False,
    "selFilterCTextColor": "#000000FF",
    "selATitleColorIsOn": False,
    "selFilterATitleColor": "#000000FF",
    "selATextColorIsOn": False,
    "selFilterATextColor": "#000000FF",
    "selScoreTextColorIsOn": False,
    "selFilterSTextColor": "#000000FF",
    "selFilterVisibleIsOn": False,
    "reqFilterBlurIsOn": False,
    "reqFilterBlur": 0,
    "reqFilterBrightIsOn": False,
    "reqFilterBright": 100,
    "reqFilterContIsOn": False,
    "reqFilterCont": 100,
    "reqFilterGrayIsOn": False,
    "reqFilterGray": 0,
    "reqFilterHueIsOn": False,
    "reqFilterHue": 0,
    "reqFilterInvertIsOn": False,
    "reqFilterInvert": 0,
    "reqFilterOpacIsOn": True,
    "reqFilterOpac": 50,
    "reqFilterSaturIsOn": False,
    "reqFilterSatur": 1,
    "reqFilterSepiaIsOn": False,
    "reqFilterSepia": 0,
    "reqBgColorIsOn": False,
    "reqOverlayOnImage": False,
    "reqFilterBgColor": "#FFFFFFFF",
    "reqBorderColorIsOn": False,
    "reqFilterBorderColor": "#000000FF",
    "reqImgBorderColorIsOn": False,
    "reqImgFilterBorderColor": "#000000FF",
    "reqCTitleColorIsOn": False,
    "reqFilterCTitleColor": "#000000FF",
    "reqCTextColorIsOn": False,
    "reqFilterCTextColor": "#000000FF",
    "reqATitleColorIsOn": False,
    "reqFilterATitleColor": "#000000FF",
    "reqATextColorIsOn": False,
    "reqFilterATextColor": "#000000FF",
    "reqScoreTextColorIsOn": False,
    "reqFilterSTextColor": "#000000FF",
    "reqFilterVisibleIsOn": False,
    "unselFilterBlurIsOn": False,
    "unselFilterBlur": 0,
    "unselFilterBrightIsOn": False,
    "unselFilterBright": 100,
    "unselFilterContIsOn": False,
    "unselFilterCont": 100,
    "unselFilterGrayIsOn": False,
    "unselFilterGray": 0,
    "unselFilterHueIsOn": False,
    "unselFilterHue": 0,
    "unselFilterInvertIsOn": False,
    "unselFilterInvert": 0,
    "unselFilterOpacIsOn": False,
    "unselFilterOpac": 100,
    "unselFilterSaturIsOn": False,
    "unselFilterSatur": 1,
    "unselFilterSepiaIsOn": False,
    "unselFilterSepia": 0,
    "unselFilterVisibleIsOn": False,
}

TEXT_STYLING: dict[str, Any] = {
    "customRowTitle": False,
    "rowTitle": "Times New Roman",
    "customRowText": False,
    "rowText": "Times New Roman",
    "customObjectTitle": False,
    "objectTitle": "Times New Roman",
    "customObjectText": False,
    "objectText": "Times New Roman",
    "customAddonTitle": False,
    "addonTitle": "Times New Roman",
    "customAddonText": False,
    "addonText": "Times New Roman",
    "customScoreText": False,
    "scoreText": "Times New Roman",
    "rowTitleTextSize": 200,
    "rowTextTextSize": 100,
    "objectTitleTextSize": 200,
    "objectTextTextSize": 100,
    "addonTitleTextSize": 200,
    "addonTextTextSize": 100,
    "scoreTextSize": 75,
    "rowTitleColor": "#000000",
    "rowTextColor": "#000000",
    "objectTitleColor": "#000000",
    "objectTextColor": "#000000",
    "addonTitleColor": "#000000",
    "addonTextColor": "#000000",
    "scoreTextColor": "#000000",
    "rowTitleAlign": "center",
    "rowTextAlign": "center",
    "objectTitleAlign": "center",
    "objectTextAlign": "center",
    "addonTitleAlign": "center",
    "addonTextAlign": "center",
    "scoreTextAlign": "center",
}

OBJECT_IMAGE_STYLING: dict[str, Any] = {
    "objectImgBorderStyle": "solid",
    "objectImgBorderWidth": 2,
    "objectImageWidth": 100,
    "objectImageMarginTop": 0,
    "objectImageMarginBottom": 0,
    "objectImgBorderRadiusTopLeft": 0,
    "objectImgBorderRadiusTopRight": 0,
    "objectImgBorderRadiusBottomRight": 0,
    "objectImgBorderRadiusBottomLeft": 0,
    "objectImgBorderRadiusIsPixels": True,
    "objectImgBorderIsOn": False,
    "objectImgOverflowIsOn": False,
    "objectImgBorderColor": "red",
    "objectImgObjectFillStyle": "",
    "objectImgObjectFillIsOn": False,
    "objectImgObjectFillHeight": 0,
    "objectImageBoxWidth": 50,
}

ROW_IMAGE_STYLING: dict[str, Any] = {
    "rowImgBorderStyle": "solid",
    "rowImgBorderWidth": 2,
    "rowImageWidth": 100,
    "rowImageMarginTop": 0,
    "rowImageMarginBottom": 0,
    "rowImgBorderRadiusTopLeft": 0,
    "rowImgBorderRadiusTopRight": 0,
    "rowImgBorderRadiusBottomRight": 0,
    "rowImgBorderRadiusBottomLeft": 0,
    "rowImgBorderRadiusIsPixels": True,
    "rowImgBorderIsOn": False,
    "rowImgOverflowIsOn": False,
    "rowImgBorderColor": "red",
    "rowImageBoxWidth": 50,
    "rowImgObjectFillStyle": "",
    "rowImgObjectFillIsOn": False,
    "rowImgObjectFillHeight": 0,
}

ADDON_IMAGE_STYLING: dict[str, Any] = {
    "useAddonImage": False,
    "addonImgBorderStyle": "solid",
    "addonImgBorderWidth": 2,
    "addonImageWidth": 100,
    "addonImageMarginTop": 0,
    "addonImageMarginBottom": 0,
    "addonImgBorderRadiusTopLeft": 0,
    "addonImgBorderRadiusTopRight": 0,
    "addonImgBorderRadiusBottomRight": 0,
    "addonImgBorderRadiusBottomLeft": 0,
    "addonImgBorderRadiusIsPixels": True,
    "addonImgBorderIsOn": False,
    "addonImgOverflowIsOn": False,
    "addonImgBorderColor": "red",
    "addonImgObjectFillStyle": "",
    "addonImgObjectFillIsOn": False,
    "addonImgObjectFillHeight": 0,
    "addonImageBoxWidth": 50,
}

BACKGROUND_STYLING: dict[str, Any] = {
    "bgColorIsOn": False,
    "backgroundColor": "#FFFFFFFF",
    "rowBgColorIsOn": False,
    "rowBgColor": "#FFFFFFFF",
    "objectBgColorIsOn": False,
    "objectBgColor": "#FFFFFFFF",
    "isBackgroundRepeat": False,
    "isBackgroundFitIn": False,
    "isBackgroundOverlay": False,
    "backgroundImage": "",
    "isRowBackgroundRepeat": False,
    "isRowBackgroundFitIn": False,
    "isRowBackgroundOverlay": False,
    "rowBackgroundImage": "",
    "isObjectBackgroundRepeat": False,
    "isObjectBackgroundFitIn": False,
    "isObjectBackgroundOverlay": False,
    "objectBackgroundImage": "",
}

OBJECT_STYLING: dict[str, Any] = {
    "objectHeight": True,
    "objectDesignIsAdvanced": False,
    "objectMargin": 10,
    "objectTextPadding": 10,
    "objectBorderStyle": "solid",
    "objectBorderWidth": 2,
    "objectBorderIsOn": False,
    "objectDropShadowH": 0,
    "objectDropShadowV": 0,
    "objectDropShadowBlur": 0,
    "objectDropShadowSpread": 0,
    "objectDropShadowIsOn": False,
    "objectUseBoxShadowIsOn": False,
    "objectBorderRadiusTopLeft": 0,
    "objectBorderRadiusTopRight": 0,
    "objectBorderRadiusBottomRight": 0,
    "objectBorderRadiusBottomLeft": 0,
    "objectBorderRadiusIsPixels": True,
    "objectOverflowIsOn": True,
    "objectDropShadowColor": "grey",
    "objectGradientIsOn": False,
    "objectGradient": "",
    "objectGradientOnSelect": "",
    "objectGradientOnReq": "",
    "objectBorderColor": "red",
    "objectBorderImage": "",
    "objectBorderImageRepeat": "stretch",
    "objectBorderImageWidth": 5,
    "objectBorderImageSliceTop": 5,
    "objectBorderImageSliceBottom": 5,
    "objectBorderImageSliceLeft": 5,
    "objectBorderImageSliceRight": 5,
    "removeSpaceAddonIsOn": False,
    "titlePaddingIsOn": False,
}

ROW_STYLING: dict[str, Any] = {
    "rowDesignIsAdvanced": False,
    "rowMargin": 10,
    "rowBodyMarginSides": 1,
    "rowBodyMarginTop": 25,
    "rowBodyMarginBottom": 25,
    "rowHeaderMarginBottom": 0,
    "rowTextPaddingY": 5,
    "rowTextPaddingX": 10,
    "rowOverflowIsOn": True,
    "rowDropShadowH": 0,
    "rowDropShadowV": 0,
    "rowDropShadowBlur": 0,
    "rowDropShadowSpread": 0,
    "rowDropShadowColor": "grey",
    "rowButtonXPadding": 0,
    "rowButtonYPadding": 0,
    "rowDropShadowIsOn": False,
    "rowUseBoxShadowIsOn": False,
    "rowBorderRadiusTopLeft": 0,
    "rowBorderRadiusTopRight": 0,
    "rowBorderRadiusBottomRight": 0,
    "rowBorderRadiusBottomLeft": 0,
    "rowBorderRadiusIsPixels": True,
    "rowBorderStyle": "solid",
    "rowBorderWidth": 2,
    "rowBorderIsOn": False,
    "rowBorderColor": "red",
    "rowGradientIsOn": False,
    "rowGradient": "",
    "rowBorderImage": "",
    "rowBorderImageRepeat": "stretch",
    "rowBorderImageWidth": 5,
    "rowBorderImageSliceTop": 5,
    "rowBorderImageSliceBottom": 5,
    "rowBorderImageSliceLeft": 5,
    "rowBorderImageSliceRight": 5,
}

ADDON_STYLING: dict[str, Any] = {
    "useAddonDesign": False,
    "addonDesignIsAdvanced": False,
    "addonMargin": 10,
    "addonTextPadding": 10,
    "addonBorderStyle": "solid",
    "addonBorderWidth": 2,
    "addonBorderIsOn": False,
    "addonDropShadowH": 0,
    "addonDropShadowV": 0,
    "addonDropShadowBlur": 0,
    "addonDropShadowSpread": 0,
    "addonDropShadowIsOn": False,
    "addonUseBoxShadowIsOn": False,
    "addonBorderRadiusTopLeft": 0,
    "addonBorderRadiusTopRight": 0,
    "addonBorderRadiusBottomRight": 0,
    "addonBorderRadiusBottomLeft": 0,
    "addonBorderRadiusIsPixels": True,
    "addonOverflowIsOn": True,
    "addonDropShadowColor": "grey",
    "addonGradientIsOn": False,
    "addonGradient": "",
    "addonGradientOnSelect": "",
    "addonGradientOnReq": "",
    "addonBorderColor": "red",
    "addonBorderImage": "",
    "addonBorderImageRepeat": "stretch",
    "addonBorderImageWidth": 5,
    "addonBorderImageSliceTop": 5,
    "addonBorderImageSliceBottom": 5,
    "addonBorderImageSliceLeft": 5,
    "addonBorderImageSliceRight": 5,
    "useAddonBackgroundImage": False,
    "addonBackgroundImage": "",
    "isAddonBackgroundFitIn": False,
    "isAddonBackgroundRepeat": False,
    "isAddonBackgroundOverlay": False,
    "addonBgColorIsOn": False,
    "addonBgColor": "#FFFFFFFF",
    "addonTitlePaddingIsOn": False,
}

MULTI_CHOICE_STYLING: dict[str, Any] = {
    "customMultiTextFont": False,
    "multiChoiceCounterPosition": 0,
    "multiChoiceCounterSize": 170,
    "multiChoiceTextFont": "Times New Roman",
    "multiChoiceTextSize": 100,
}

POINT_BAR_STYLING: dict[str, Any] = {
    "barTextPadding": 17,
    "barTextMargin": 0,
    "customBarTextFont": False,
    "barTextFont": "Times New Roman",
    "barPadding": 0,
    "barMargin": 0,
    "barTextSize": 15,
    "barTextColor": "#000000",
    "barPointPos": "#FF0000FF",
    "barPointNeg": "#FF0000FF",
    "barIconColor": "#0000008A",
    "barBackgroundColor": "#FFFFFFFF",
    "barBacktroundImage": "",
    "isBarBgRepeat": False,
    "isBarBgFitIn": False,
    "isBarBgOverlay": False,
}

BACKPACK_STYLING: dict[str, Any] = {
    "useBackpackDesign": False,
    "backpackBgColor": "#FFFFFF",
    "isBackpackBgRepeat": False,
    "isBackpackBgFitIn": False,
    "backpackBgImage": "",
    "backPackWidth": 1400,
}

STYLING: dict[str, Any] = {
    **FILTER_STYLING,
    **TEXT_STYLING,
    **OBJECT_IMAGE_STYLING,
    **ROW_IMAGE_STYLING,
    **ADDON_IMAGE_STYLING,
    **BACKGROUND_STYLING,
    **OBJECT_STYLING,
    **ROW_STYLING,
    **ADDON_STYLING,
    **MULTI_CHOICE_STYLING,
    **POINT_BAR_STYLING,
    **BACKPACK_STYLING,
}

_DEFAULT_ROW_TEXT = (
    "This is a row, and inside of it, you can place choices. On both rows and choices Requirements can be placed, "
    "which will block a row from being viewed, or make the player unable to select a choice, depending on either "
    "Point-types or the Ids of other choices. Point-types can be made in Features then Manage Points. Hovering over "
    "buttons will explain what they do. The Design of the project can be changed in 'Modify Design' at the side "
    "navigation bar, and private styling for each row can be turned on in the rows Settings. Default text like this "
    "can be turned off in Features -> Manage Defaults."
)
_DEFAULT_CHOICE_TEXT = (
    "This is a Choice, and inside of it, you can place images and text. Scores can be added to it, and have Point-types "
    "attached. Addons can be added underneath the image and text. In the Functions at the bottom of the choice, there "
    "is an array of different things that can be done. Default text like this can be turned off in Features then Manage Defaults."
)
_DEFAULT_ADDON_TEXT = (
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's "
    "standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make "
    "a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, "
    "remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing "
    "Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions "
    "of Lorem Ipsum."
)

DEFAULT_APP: dict[str, Any] = {
    "version": ICCPLUS_VERSION,
    "isEditModeOnAll": True,
    "isPointerCursor": False,
    "importedChoicesIsOpen": True,
    "curVolume": 100,
    "isMute": False,
    "showMusicPlayer": False,
    "fadeTransitionColor": "#000000FF",
    "fadeTransitionTime": 0.25,
    "fadeTransitionIsOn": False,
    "hideBackpackBtn": 0,
    "btnBackpackIsOn": 0,
    "showAllAddons": 0,
    "tmpRow": [],
    "tmpChoice": [],
    "tmpRequired": [],
    "tmpScore": [],
    "tmpAddon": [],
    "tmpGroup": [],
    "tmpDesignGroup": [],
    "rowIdLength": 4,
    "objectIdLength": 4,
    "words": [],
    "groups": [],
    "rowDesignGroups": [],
    "objectDesignGroups": [],
    "objectsPerRow": "default",
    "globalRequirements": [],
    "soundEffects": [],
    "googleFonts": [],
    "customFonts": [],
    "customCSS": "",
    "compressImageAuto": False,
    "useTextEditor": True,
    "useToolbarBtn": False,
    "useChoiceEditBtn": True,
    "hideScoresUpdated": False,
    "hideChoiceDT": False,
    "hideImages": False,
    "preloadImages": False,
    "preloadExternalImages": False,
    "useVW": False,
    "addPrefix": True,
    "activated": [],
    "rows": [],
    "pointTypes": [],
    "variables": [],
    "mdObjects": [],
    "categories": [],
    "printThis": False,
    "autoSaveIsOn": False,
    "autoSaveInterval": 10,
    "buildAutoSaveIsOn": False,
    "buildAutoSaveInterval": 10,
    "tooltipDelay": 1000,
    "checkDeleteRow": True,
    "checkDeleteObject": False,
    "checkSelectAll": False,
    "defaultRowTitle": "Row",
    "defaultRowText": _DEFAULT_ROW_TEXT,
    "defaultChoiceTitle": "Choice",
    "defaultChoiceText": _DEFAULT_CHOICE_TEXT,
    "defaultBeforePoint": "Cost:",
    "defaultAfterPoint": "points",
    "defaultBeforeReq": "Required:",
    "defaultAfterReq": "choice",
    "defaultAddonTitle": "Addon",
    "defaultAddonText": _DEFAULT_ADDON_TEXT,
    "enableShortcut": True,
    "orderOrReqText": "0",
    "defaultOrReq": "of",
    "orderSelReqText": "0",
    "defaultSelReq": "choice from",
    "defaultRowTemplate": 1,
    "defaultRowWidth": "col-md-3",
    "defaultRowJustify": "start",
    "defaultRowAllowedChoices": 0,
    "defaultChoiceTemplate": 1,
    "defaultChoiceWidth": "",
    "defaultChoiceMaxNum": 99,
    "defaultAddonJustify": "start",
    "defaultAddonTemplate": 1,
    "defaultAddonWidth": "col-12",
    "defaultUseSeperateAddon": False,
    "defaultUseShowAddon": False,
    "defaultUseHideAddon": False,
    "defaultUseShowScore": True,
    "defaultUseHideValue": False,
    "defaultUseShowReq": False,
    "cropperPosition": 4,
    "enableSearch": True,
    "useDesignGroupBtn": False,
    "smallerScreenPx": 720,
    "enableHalfRow": False,
    "minimizeTemplate": True,
    "hideRowMenu": False,
    "viewerConfig": {
        "title": "CYOA Plus 2",
        "favicon": "",
        "loadingType": "ind1",
        "loadingBgColor": "#232428",
        "loadingBgImage": "",
        "loadingCircleColor": "#d5c999",
        "loadingTrackColor": "#3c3c3c",
        "loadingText": "Loading",
        "loadingTextColor": "#d5c999",
        "loadingTextFont": "Arial",
        "loadingTextShadow": "#fff000",
        "useSeparateImages": False,
        "useLocalViewer": False,
    },
    "backpack": [{
        "index": 0,
        "id": "default_backpack_row",
        "isBackpack": True,
        "title": "Result",
        "debugTitle": "",
        "titleText": "",
        "objectWidth": "col-md-3",
        "image": "",
        "template": 1,
        "rowJustify": "start",
        "isButtonRow": False,
        "buttonType": True,
        "buttonId": "",
        "buttonText": "Click",
        "buttonRandom": False,
        "buttonRandomNumber": 1,
        "isResultRow": True,
        "resultGroupId": "",
        "isInfoRow": True,
        "defaultAspectWidth": 1,
        "defaultAspectHeight": 1,
        "allowedChoices": 0,
        "currentChoices": 0,
        "requireds": [],
        "isEditModeOn": False,
        "isRequirementOpen": False,
        "objects": [],
        "rowDesignGroups": [],
    }],
    "styling": STYLING,
}


def default_project() -> dict[str, Any]:
    """Return an exact deep copy of ICC Plus 2.10.6 ``defaultApp``."""
    return copy.deepcopy(DEFAULT_APP)


def default_export_project() -> dict[str, Any]:
    """Return the object emitted by ICC Plus 2.10.6 Save to Disk on a new project.

    Save to Disk runs ``app.activated = getSelectedObjectId().split(',')``.
    For an empty build ``getSelectedObjectId()`` is ``''``, so this is ``['']``.
    """
    project = default_project()
    project["activated"] = [""]
    project["version"] = ICCPLUS_VERSION
    return project


def json_stringify(value: Any) -> str:
    """Match JSON.stringify for ICC Plus project data used by this package."""
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), allow_nan=False)


def default_export_text() -> str:
    return json_stringify(default_export_project())


def default_export_bytes() -> bytes:
    return default_export_text().encode("utf-8")
